"""empty message

Revision ID: 7c43ee3dd169
Revises: f36e49c6c868
Create Date: 2021-06-11 14:40:00.684533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c43ee3dd169'
down_revision = 'f36e49c6c868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_swap_asset1_id_asset2_id_timestamp_desc', 'swap', ['asset1_id', 'asset2_id', sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_swap_asset1_id_asset2_id_timestamp_desc', table_name='swap')
    # ### end Alembic commands ###
