"""empty message

Revision ID: f36e49c6c868
Revises: 
Create Date: 2021-06-10 16:35:55.066965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36e49c6c868'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=66), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('precision', sa.Integer(), nullable=False),
    sa.Column('trade_volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('swap',
    sa.Column('id', sa.Numeric(precision=20), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('xor_fee', sa.Numeric(precision=20), nullable=False),
    sa.Column('asset1_id', sa.Integer(), nullable=False),
    sa.Column('asset2_id', sa.Integer(), nullable=False),
    sa.Column('asset1_amount', sa.Numeric(precision=33), nullable=False),
    sa.Column('asset2_amount', sa.Numeric(precision=33), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('filter_mode', sa.String(length=32), nullable=False),
    sa.Column('swap_fee_amount', sa.Numeric(precision=21), nullable=True),
    sa.ForeignKeyConstraint(['asset1_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['asset2_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_swap_asset1_id_asset2_id', 'swap', ['asset1_id', 'asset2_id'], unique=False)
    op.create_index(op.f('ix_swap_timestamp'), 'swap', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swap_timestamp'), table_name='swap')
    op.drop_index('idx_swap_asset1_id_asset2_id', table_name='swap')
    op.drop_table('swap')
    op.drop_table('asset')
    # ### end Alembic commands ###
